version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROMETHEUS_VERSION: ${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"
    restart: unless-stopped
    container_name: prometheus